/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2.Interfaces;

import java.awt.Frame;
import java.awt.TextField;
import static java.awt.image.ImageObserver.HEIGHT;
import javaapplication2.Classes.Entry;
import javaapplication2.Classes.EntryList;
import javaapplication2.Classes.Member;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author juju-
 */
public class EditEntryDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditMemberDialog
     */
    public EditEntryDialog(java.awt.Frame parentFrame, boolean modal) {
        super(parentFrame, modal);
        setParentFrame(parentFrame);
        
        initComponents();
        CashFlowFrame cashFlowFrame = (CashFlowFrame)parentFrame;
        
        Entry entry = cashFlowFrame.getEntryList().getEntryByKey(cashFlowFrame.getEditedEntryKey());
        txtfield_date.setText(entry.getDate());
        txtfield_description.setText(entry.getDescription());
        txtfield_value.setText(String.format("%.2f", entry.getValue(false)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void setParentFrame(Frame parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    private Frame getParentFrame() {
        return this.parentFrame;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfield_date = new javax.swing.JTextField();
        txtfield_description = new javax.swing.JTextField();
        txtfield_value = new javax.swing.JTextField();
        btn_edit_entry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DESCRIÇÃO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VALOR");

        txtfield_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_dateActionPerformed(evt);
            }
        });

        txtfield_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_descriptionActionPerformed(evt);
            }
        });

        txtfield_value.setToolTipText("(XX) XXXXX-XXXX");
        txtfield_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_valueActionPerformed(evt);
            }
        });

        btn_edit_entry.setText("OK");
        btn_edit_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_entryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_edit_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfield_value, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(txtfield_description, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfield_date, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfield_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtfield_description, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfield_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_edit_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_dateActionPerformed

    private void txtfield_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_descriptionActionPerformed

    private void txtfield_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_valueActionPerformed

    private void btn_edit_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_entryActionPerformed
        // TODO add your handling code here:
        String newDate, description, newDescription, value, newValue;
        Double newValueNum;
        boolean error;
        
        description = txtfield_description.getText();
        value = txtfield_value.getText();
        
        CashFlowFrame frame = (CashFlowFrame)getParentFrame();
        int editedEntryKey = frame.getEditedEntryKey();
        int editedRow = frame.getEditedRow();
        
        newDate = txtfield_date.getText().replaceAll("\\s+", "");
        newDescription = txtfield_description.getText();
        newValue = txtfield_value.getText().replaceAll("\\s+", "");
        newValueNum = Double.parseDouble(newValue.replace(",", "."));
        newValue = String.format("%.2f", newValueNum);
                
        error = checkError(newDate, newValue);
        
        if (!error) {
            EntryList entryList = frame.getEntryList();
            JTable jTable = frame.getJTable();
            Entry editedEntry = entryList.getEntryByKey(editedEntryKey);
        
            if (!editedEntry.getDescription().equals(description)) {
                entryList.updateEntry(editedEntryKey, 1, newDescription);
                jTable.setValueAt(newDescription, editedRow, 2);
            }
        
            if (!Double.toString(editedEntry.getValue(false)).equals(newValue)) {
                entryList.updateEntry(editedEntryKey, 2, newValueNum);
                if(jTable.getValueAt(editedRow, 3).toString().isEmpty()) jTable.setValueAt("-" + newValue, editedRow, 4);
                else jTable.setValueAt(newValue, editedRow, 3);
            }
            
            if (!editedEntry.getDate().equals(newDate)) {
                jTable.setValueAt(newDate, editedRow, 1);
                entryList.updateEntry(editedEntryKey, 0, newDate);
            }
            
            frame.updateTxt(entryList.getIn(), entryList.getOut());
        }        
    }//GEN-LAST:event_btn_edit_entryActionPerformed

    private boolean checkError(String date, String value) {
        boolean error = false;
        
        if (value.isEmpty()) {
            JOptionPane.showMessageDialog(parentFrame, "Insira o valor!", "Alerta", HEIGHT);
            error = true;
        }
        
        if (!value.matches("[0-9]+([,.][0-9]{2})?")) {
            JOptionPane.showMessageDialog(parentFrame, "Formato do valor incorreto!", "Alerta", HEIGHT);
            error = true;
        }
        
        if(!date.matches("\\d{1,2}/{1}\\d{1,2}/{1}\\d{4}")) {
            JOptionPane.showMessageDialog(parentFrame, "Formato de data incorreto!", "Alerta", HEIGHT);
            error = true;
        }
               
        return error;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditEntryDialog dialog = new EditEntryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Frame parentFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtfield_date;
    private javax.swing.JTextField txtfield_description;
    private javax.swing.JTextField txtfield_value;
    // End of variables declaration//GEN-END:variables
}
