/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2.Interfaces;
import java.awt.Frame;
import javax.swing.JTable;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javaapplication2.Classes.Member;
import javaapplication2.Classes.MemberList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juju-
 */
public class SearchMemberDialog extends javax.swing.JDialog {

    /**
     * Creates new form SearchMemberDialog
     */
    public SearchMemberDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setParentFrame(parent);
    }
    
    private void setParentFrame(Frame parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    private Frame getParentFrame() {
        return this.parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radiobtn_name = new javax.swing.JRadioButton();
        radiobtn_address = new javax.swing.JRadioButton();
        radiobtn_number = new javax.swing.JRadioButton();
        radiobtn_birthdate = new javax.swing.JRadioButton();
        radiobtn_role = new javax.swing.JRadioButton();
        radiobtn_register = new javax.swing.JRadioButton();
        txtfield_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar membro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonGroup1.add(radiobtn_name);
        radiobtn_name.setText("Nome");
        radiobtn_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_nameActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_address);
        radiobtn_address.setText("Endereço");
        radiobtn_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_addressActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_number);
        radiobtn_number.setText("Telefone");
        radiobtn_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_numberActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_birthdate);
        radiobtn_birthdate.setText("Data de nascimento");
        radiobtn_birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_birthdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_role);
        radiobtn_role.setText("Cargo");
        radiobtn_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_roleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_register);
        radiobtn_register.setText("Cadastro");
        radiobtn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_registerActionPerformed(evt);
            }
        });

        btn_search.setText("Pesquisar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfield_search)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtn_name)
                            .addComponent(radiobtn_birthdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtn_address)
                            .addComponent(radiobtn_role))
                        .addGap(25, 25, 25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(radiobtn_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radiobtn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(radiobtn_name)
                            .addGap(18, 18, 18)
                            .addComponent(radiobtn_birthdate))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(radiobtn_number)
                            .addGap(18, 18, 18)
                            .addComponent(radiobtn_register)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radiobtn_address)
                        .addGap(18, 18, 18)
                        .addComponent(radiobtn_role)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtn_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_nameActionPerformed

    private void radiobtn_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_addressActionPerformed

    private void radiobtn_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_numberActionPerformed

    private void radiobtn_birthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_birthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_birthdateActionPerformed

    private void radiobtn_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_roleActionPerformed

    private void radiobtn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_registerActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        boolean[] radiobtn = {radiobtn_name.isSelected(), radiobtn_address.isSelected(), radiobtn_number.isSelected(), 
            radiobtn_birthdate.isSelected(), radiobtn_role.isSelected(), radiobtn_register.isSelected()};
        MemberListFrame memberListFrame = (MemberListFrame)getParentFrame();
        MemberList memberList = memberListFrame.getMemberList();
        List<Member> searchResult = new ArrayList<Member>();
        boolean error = false;
        
        if (txtfield_search.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(parentFrame, "O campo de busca está em branco!", "Alerta", HEIGHT);
            error = true;
        }
        
        if(!radiobtn_name.isSelected() && !radiobtn_address.isSelected() && !radiobtn_number.isSelected() &&
                !radiobtn_birthdate.isSelected() && !radiobtn_role.isSelected() && !radiobtn_register.isSelected()) {
            JOptionPane.showMessageDialog(parentFrame, "Selecione o tipo de busca!", "Alerta", HEIGHT);
            error = true;
        }
        
        if(!error) {
            for(int i=0; i<radiobtn.length; i++) {
                if (radiobtn[i] == true)
                {
                    searchResult = memberList.objectSearch(i, txtfield_search.getText());
                    break;
                }
            }
            memberListFrame.updateTable(searchResult, (DefaultTableModel)memberListFrame.getJTable().getModel());
            memberListFrame.updateTxt(Integer.toString(searchResult.size()));
            memberListFrame.getJTable().validate();
        }
    }//GEN-LAST:event_btn_searchActionPerformed
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        MemberListFrame memberListFrame = (MemberListFrame)getParentFrame();
        MemberList memberList = memberListFrame.getMemberList();
        DefaultTableModel defaultTableModel = (DefaultTableModel)memberListFrame.getJTable().getModel();
        
        memberListFrame.updateTable(memberList, defaultTableModel);
        memberListFrame.getJTable().validate();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMemberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchMemberDialog dialog = new SearchMemberDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Frame parentFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radiobtn_address;
    private javax.swing.JRadioButton radiobtn_birthdate;
    private javax.swing.JRadioButton radiobtn_name;
    private javax.swing.JRadioButton radiobtn_number;
    private javax.swing.JRadioButton radiobtn_register;
    private javax.swing.JRadioButton radiobtn_role;
    private javax.swing.JTextField txtfield_search;
    // End of variables declaration//GEN-END:variables
}
